application: trafficcam-fetcher
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /cleanUp
  script: cleanup.py
  login: admin

- url: /cleanQ
  script: cleanup.py
  login: admin

- url: /fetchPics
  script: fetch.py
  login: admin
  
- url: /fetchQ
  script: fetch.py
  login: admin
    
- url: /serve_single_pic/(.*)
  script: serve.py

- url: /serve_single_pic_GTUG_100/(.*)
  script: serve.py

- url: /serve_all_pics
  script: serve.py
  login: admin
  
- url: /image/(.*)
  script: serve.py
  login: admin

- url: /init
  script: init_ds.py
  login: admin

- url: /cleanup
  script: cleanup.py
  login: admin

- url: /*
  script: main.py
  
- url: /admin
  script: main.py
  login: admin
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
 
